routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});
Route::group(['middleware' => 'auth'], function(){
    Route::resource('mgov-ceps', 'MgovCepsController');

    Route::resource('mgov-locations', 'MgovLocationsController');

    Route::post('import-excel-mgov-template', 'ImportExcelMgovTemplateController@store')->name('import-excel-mgov-template.store');
    Route::post('create-lat-lng-from-mgov-ceps', 'GeolocationController@getLatitudeLongitude')->name('create-lat-lng-from-mgov-ceps.location');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/MgovCep.php
<?php

namespace Mgov\Models;

use Illuminate\Database\Eloquent\Model;
use Mgov\Validators\ValidatorDataFunctions;

class MgovCep extends Model
{
    use ValidatorDataFunctions;

    protected $table = 'mgov_ceps';
    protected $fillable = [
        'mgov_id',
        'cep',
        'pais',
    ];

    public function location()
    {
        return $this->hasMany('Mgov\Models\MgovLocation', 'mgov_ceps_id', 'id');
    }

    public function setCepAttribute($value)
    {
        $this->attributes['cep'] = $this->returnOnlyNumbers($value);
    }

    public function formatCepAttribute($value)
    {
        if (strlen($value) ===  8) {
            return preg_replace('/(\d{5})(\d{3})/', '$1-$2', $value);
        }
        return $value;
    }
}

app/Http/Controllers/Api/MgovCepsController.php
<?php

namespace Mgov\Http\Controllers\Api;

use Illuminate\Http\Request;
use Mgov\Http\Controllers\Controller;
use Mgov\Http\Controllers\ControllerTrait;

use Mgov\Services\MgovCepService;
use Mgov\Repositories\Contracts\MgovCepRepository;

class MgovCepsController extends Controller
{
    use ControllerTrait;

    public $service;
    public $repository;

    public function __construct(MgovCepService $service, MgovCepRepository $repository)
    {
        $this->service = $service;
        $this->repository = $repository;
    }
}

app/Http/Controllers/MgovCepsController.php
<?php

namespace Mgov\Http\Controllers;

use Illuminate\Http\Request;

use Mgov\Services\MgovCepService;
use Mgov\Repositories\Contracts\MgovCepRepository;

class MgovCepsController extends Controller
{
    use ControllerTrait {
        index as traitIndex;
        destroy as traitDestroy;
        store as traitStore;
        show as traitShow;
        update as traitUpdate;
    }

    public $service;
    public $repository;

    public function __construct(MgovCepService $service, MgovCepRepository $repository)
    {
        $this->service = $service;
        $this->repository = $repository;
    }

    public function index()
    {
        $results = $this->traitIndex();
        return view('mgov_ceps.index', compact('results'));
    }

    public function show($id)
    {
        $result = $this->traitShow($id);
        return view('mgov_ceps.show', compact('result'));
    }

    public function create()
    {
        return view('mgov_ceps.create');
    }

    public function store(Request $request)
    {
        $result = $this->traitStore($request);
        return view('mgov_ceps.show', compact('result'));
    }

    public function edit($id)
    {
        $result = $this->traitShow($id);
        return view('mgov_ceps.edit', compact('result'));
    }

    public function update(Request $request, $id)
    {
        $result = $this->traitUpdate($request, $id);
        return view('mgov_ceps.show', compact('result'));
    }

    public function destroy($id)
    {
        $results = $this->traitDestroy($id);
        return response()->redirectToRoute('mgov-ceps.index');
    }
}

resources/views/mgov_ceps/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="d-flex">Mgov Ceps</h2>
            <hr>
        </div><!-- ./col-12 -->
        <div class="col-12">
            <form method="post" action="{{ route('mgov-ceps.store') }}">
                {!! csrf_field() !!}
                <div class="form-group">
                    <label for="mgov_id">ID da Mgov</label>
                    <input type="text" name="mgov_id" id="mgov_id" class="form-control" placeholder="Exemplo: 05736">
                </div>
                <div class="form-group">
                    <label for="cep">CEP</label>
                    <input type="text" name="cep" id="cep" class="form-control" placeholder="Exemplo: 13212-412">
                </div>
                <div class="form-group">
                    <label for="pais">País</label>
                    <input type="text" name="pais" id="pais" class="form-control" placeholder="Exemplo: Brasilzão">
                </div>
                <button class="btn btn-block btn-success" type="submit">Salvar</button>
            </form> <br><br>
            <a href="{{ route('mgov-ceps.index') }}">Voltar para a listagem</a> <br><br>
        </div><!-- ./col-12 -->
    </div><!-- ./row -->
</div><!-- ./container -->
@endsection

resources/views/mgov_ceps/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="d-flex">Mgov Ceps - Editar o id {{ $result->id }}</h2>
            <hr>
        </div><!-- ./col-12 -->
        <div class="col-12">
            <form method="post" action="{{ route('mgov-ceps.update', $result->id) }}">
                {!! csrf_field() !!}
                <input name="_method" type="hidden" value="PUT">
                <div class="form-group">
                    <label for="mgov_id">ID da Mgov</label>
                    <input type="text" name="mgov_id" id="mgov_id" class="form-control" placeholder="Exemplo: 05736" value="{{ $result->mgov_id}}">
                </div>
                <div class="form-group">
                    <label for="cep">CEP</label>
                    <input type="text" name="cep" id="cep" class="form-control" placeholder="Exemplo: 13212-412" value="{{ $result->cep}}">
                </div>
                <div class="form-group">
                    <label for="pais">País</label>
                    <input type="text" name="pais" id="pais" class="form-control" placeholder="Exemplo: Brasilzão" value="{{ $result->pais}}">
                </div>
                <button class="btn btn-block btn-success" type="submit">Salvar</button>
            </form> <br><br>
            <a href="{{ route('mgov-ceps.index') }}">Voltar para a listagem</a> <br><br>
        </div><!-- ./col-12 -->
    </div><!-- ./row -->
</div><!-- ./container -->
@endsection

resources/views/mgov_ceps/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="d-flex">Mgov Ceps</h2>
            <div class="d-flex">
                <div class="align-items-center">
                    <a class="btn btn-link" href="{{route('mgov-ceps.create')}}">Criar novo Mgov Cep - Id</a>
                </div>
                <div class="ml-auto">
                    <form enctype="multipart/form-data" method="post" action="{{ route('import-excel-mgov-template.store') }}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <input type="file" name="file" id="file" class="form-control" aria-describedby="Selecione uma Planilha">
                            <button type="submit" class="btn btn-link">Enviar planilha</button>
                            <small id="helpId" class="text-muted">Selecione um arquivo .xls ou .xlsx</small>
                        </div>
                    </form>
                </div>

            </div>
            <hr>
        </div><!-- ./col-12 -->
        <div class="col-12">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Mgov ID</th>
                        <th>CEP</th>
                        <th>País</th>
                        <th>Excluir?</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($results as $result)
                    <tr>
                        <td><a class="btn btn-link" href="{{ route('mgov-ceps.show', $result->id) }}">{{ $result->id }}</a></td>
                        <td>{{ $result->mgov_id }}</td>
                        <td>{{ $result->formatCepAttribute($result->cep) }}</td>
                        <td>{{ $result->pais }}</td>
                        <td>
                            <form action="{{ route('mgov-ceps.destroy', $result->id) }}" class="form-horizontal" method="post" style="display: inline-block">
                                {!! csrf_field() !!}
                                <input type="hidden" name="_method" value="DELETE">
                                <button type="submit" class="btn btn-secondary">
                                    <span>
                                        <i class="fa fa-ban" aria-hidden="true"></i>
                                    </span>
                                </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <footer>
                {{ $results->render('vendor.pagination.bootstrap-4') }}
            </footer>
        </div><!-- ./col-12 -->
    </div><!-- ./row -->
</div><!-- ./container -->
@endsection

resources/views/mgov_ceps/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="d-flex">Mgov Ceps</h2>
            <hr>
        </div><!-- ./col-12 -->
        <div class="col-12">
            ID: {{ $result->id }} <br />
            Mgov Id: {{ $result->mgov_id }} <br />
            CEP: {{ $result->formatCepAttribute($result->cep) }} <br />
            País: {{ $result->pais }} <br /><br /><br />
            <a href="{{ route('mgov-ceps.index') }}">Voltar para a listagem</a> <br><br>
            <a href="{{ route('mgov-ceps.edit', $result->id) }}">Editar o item</a>
        </div><!-- ./col-12 -->
    </div><!-- ./row -->
</div><!-- ./container -->
@endsection