routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});
Route::group(['middleware' => 'auth'], function(){
    Route::resource('mgov-ceps', 'MgovCepsController');

    Route::resource('mgov-locations', 'MgovLocationsController');

    Route::post('import-excel-mgov-template', 'ImportExcelMgovTemplateController@store')->name('import-excel-mgov-template.store');
    Route::post('create-lat-lng-from-mgov-ceps', 'GeolocationController@getLatitudeLongitude')->name('create-lat-lng-from-mgov-ceps.location');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/MgovLocation.php
<?php

namespace Mgov\Models;

use Illuminate\Database\Eloquent\Model;

class MgovLocation extends Model
{
    protected $table = 'mgov_locations';
    protected $fillable = [
        'latitude',
        'longitude',
        'mgov_ceps_id'
    ];

    public function mgovCep()
    {
        return $this->belongsTo('Mgov\Models\MgovCep', 'mgov_ceps_id', 'id');
    }
}

app/Http/Controllers/Api/MgovLocationsController.php
<?php

namespace Mgov\Http\Controllers\Api;

use Illuminate\Http\Request;
use Mgov\Http\Controllers\Controller;
use Mgov\Http\Controllers\ControllerTrait;

use Mgov\Services\MgovLocationService;
use Mgov\Repositories\Contracts\MgovLocationRepository;

class MgovLocationsController extends Controller
{
    use ControllerTrait;

    public $service;
    public $repository;

    public function __construct(MgovLocationService $service, MgovLocationRepository $repository)
    {
        $this->service = $service;
        $this->repository = $repository;
    }
}

app/Http/Controllers/MgovLocationsController.php
<?php

namespace Mgov\Http\Controllers;

use Illuminate\Http\Request;

use Mgov\Services\MgovLocationService;
use Mgov\Repositories\Contracts\MgovLocationRepository;

class MgovLocationsController extends Controller
{
    use ControllerTrait {
        index as traitIndex;
        destroy as traitDestroy;
        store as traitStore;
        show as traitShow;
        update as traitUpdate;
    }

    public $service;
    public $repository;

    public function __construct(MgovLocationService $service, MgovLocationRepository $repository)
    {
        $this->service = $service;
        $this->repository = $repository;
    }

    public function index()
    {
        $results = $this->traitIndex();
        return view('mgov_locations.index', compact('results'));
    }

    public function create()
    {
        return view('mgov_locations.create');
    }

    public function edit($id)
    {
        $result = $this->traitShow($id);
        return view('mgov_locations.edit', compact('result'));
    }

    public function show($id)
    {
        $result = $this->traitShow($id);
        return view('mgov_locations.show', compact('result'));
    }

    public function store(Request $request)
    {
        $result = $this->traitStore($request);
        return view('mgov_locations.show', compact('result'));
    }

    public function update(Request $request, $id)
    {
        $result = $this->traitUpdate($request, $id);
        return view('mgov_locations.show', compact('result'));
    }

    public function destroy($id)
    {
        $results = $this->traitDestroy($id);
        return response()->redirectToRoute('mgov-locations.index');
    }
}

resources/views/mgov_locations/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="d-flex">Mgov Locations</h2>
            <hr>
        </div><!-- ./col-12 -->
        <div class="col-12">
            <form method="post" action="{{ route('mgov-locations.store') }}">
                {!! csrf_field() !!}
                <div class="form-group">
                    <label for="mgov_ceps_id">ID da Mgov Cep Id (se não sabe, vai lá na Mgov Cep consultar!)</label>
                    <input type="text" name="mgov_ceps_id" id="mgov_ceps_id" class="form-control" placeholder="Exemplo: 1 (como assim não sabe o id??? hahaha)">
                </div>
                <div class="form-group">
                    <label for="latitude">Latitude</label>
                    <input type="text" name="latitude" id="latitude" class="form-control" placeholder="Exemplo: -23.1734144">
                    <small id="helpId" class="text-muted">ATENÇÃO, não se preocupe em digitar uma latitude errada, pois, antes de salvar eu vou verificar se a latitude bate com o que tem no Google Maps (desculpe se confio mais nele do que em você, rsrs).</small>
                </div>
                <div class="form-group">
                    <label for="longitude">Longitude</label>
                    <input type="text" name="longitude" id="longitude" class="form-control" placeholder="Exemplo: -46.9619862">
                    <small id="helpId" class="text-muted">ATENÇÃO, não se preocupe em digitar uma longitude errada, pois, antes de salvar eu vou verificar se a latitude bate com o que tem no Google Maps (desculpe se confio mais nele do que em você, rsrs).</small>
                </div>
                <button class="btn btn-block btn-success" type="submit">Salvar</button>
            </form> <br><br>
            <a href="{{ route('mgov-locations.index') }}">Voltar para a listagem</a> <br><br>
        </div><!-- ./col-12 -->
    </div><!-- ./row -->
</div><!-- ./container -->
@endsection

resources/views/mgov_locations/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="d-flex">Mgov Ceps - Editar o id {{ $result->id }}</h2>
            <hr>
        </div><!-- ./col-12 -->
        <div class="col-12">
            <form method="post" action="{{ route('mgov-locations.update', $result->id) }}">
                {!! csrf_field() !!}
                <input name="_method" type="hidden" value="PUT">
                <div class="form-group">
                    <label for="mgov_ceps_id">ID da Mgov Cep Id (se não sabe, vai lá na Mgov Cep consultar!)</label>
                    <input type="text" name="mgov_ceps_id" id="mgov_ceps_id" class="form-control" placeholder="Exemplo: 1 (como assim não sabe o id??? hahaha)" value="{{ $result->mgov_ceps_id}}">
                    <small id="helpId" class="text-muted">ATENÇÃO, não se preocupe em digitar uma latitude errada, pois, antes de salvar eu vou verificar se a latitude bate com o que tem no Google Maps (desculpe se confio mais nele do que em você, rsrs).</small>
                </div>
                <div class="form-group">
                    <label for="latitude">Latitude</label>
                    <input type="text" name="latitude" id="latitude" class="form-control" placeholder="Exemplo: -23.1734144" value="{{ $result->latitude}}">
                </div>
                <div class="form-group">
                    <label for="longitude">Longitude</label>
                    <input type="text" name="longitude" id="longitude" class="form-control" placeholder="Exemplo: -46.9619862" value="{{ $result->longitude}}">
                    <small id="helpId" class="text-muted">ATENÇÃO, não se preocupe em digitar uma longitude errada, pois, antes de salvar eu vou verificar se a latitude bate com o que tem no Google Maps (desculpe se confio mais nele do que em você, rsrs).</small>
                </div>
                <button class="btn btn-block btn-success" type="submit">Salvar</button>
            </form> <br><br>
            <a href="{{ route('mgov-locations.index') }}">Voltar para a listagem</a> <br><br>
        </div><!-- ./col-12 -->
    </div><!-- ./row -->
</div><!-- ./container -->
@endsection

resources/views/mgov_locations/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="d-flex">Mgov Locations</h2>
            <div class="d-flex">
                <div class="align-items-center">
                    <a class="btn btn-link" href="{{route('mgov-locations.create')}}">Criar uma nova Geolocalização para determinado MgovId</a>
                </div>
                <div class="ml-auto">
                    <form method="post" action="{{ route('create-lat-lng-from-mgov-ceps.location') }}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <button type="submit" class="btn btn-link">Atualizar</button>
                            <small id="helpId" class="text-muted">Nesta opção você atualiza a localização de acordo com todos os ceps que estão na tabela mgov_ceps. Esse processo leva um tempo, por isso, no fim, você receberá um e-mail avisando o termino.</small>
                        </div>
                    </form>
                </div><!-- ml-auto -->
            </div><!-- d-flex -->
            <hr>
        </div><!-- ./col-12 -->
        <div class="col-12">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>CEP</th>
                        <th>Latitude</th>
                        <th>Longitude</th>
                        <th>Excluir?</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($results as $result)
                    <tr>
                        <td><a class="btn btn-link" href="{{ route('mgov-locations.show', $result->id) }}">{{ $result->id }}</a></td>
                        <td>{{ isset($result->mgovCep->cep)? $result->mgovCep->cep:'Ooops... Não consegui encontrar o cep.' }}</td>
                        <td>{{ $result->latitude }}</td>
                        <td>{{ $result->longitude }}</td>
                        <td>
                            <form action="{{ route('mgov-locations.destroy', $result->id) }}" class="form-horizontal" method="post" style="display: inline-block">
                                {!! csrf_field() !!}
                                <input type="hidden" name="_method" value="DELETE">
                                <button type="submit" class="btn btn-secondary">
                                    <span>
                                        <i class="fa fa-ban" aria-hidden="true"></i>
                                    </span>
                                </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            <footer>
                {{ $results->render('vendor.pagination.bootstrap-4') }}
            </footer>
        </div><!-- ./col-12 -->
    </div><!-- ./row -->
</div><!-- ./container -->
@endsection

resources/views/mgov_locations/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="d-flex">Mgov Locations</h2>
            <hr>
        </div><!-- ./col-12 -->
        <div class="col-12">
            ID: {{ $result->id }} <br />
            CEP: {{ isset($result->mgovCep->cep)? $result->mgovCep->cep:'Ooops... Não consegui encontrar o cep.' }} <br />
            Latitude: {{ $result->latitude }} <br />
            Longitude: {{ $result->longitude }} <br /><br /><br />
            <a href="{{ route('mgov-locations.index') }}">Voltar para a listagem</a> <br><br>
            <a href="{{ route('mgov-locations.edit', $result->id) }}">Editar o item</a>
        </div><!-- ./col-12 -->
    </div><!-- ./row -->
</div><!-- ./container -->
@endsection